CREATE SEQUENCE public.COMPANY_ID_SEQ START 1;

CREATE SEQUENCE public.USER_ID_SEQ START 1;

CREATE TABLE public.USER (
    USER_ID               VARCHAR(10)  NOT NULL DEFAULT nextval('USER_ID_SEQ')
  , EMAIL                 VARCHAR(50)  NOT NULL
  , COMPANY_ID            VARCHAR(10)  NOT NULL
  , LASTNAME_KANA         VARCHAR(50)
  , FIRSTNAME_KANA        VARCHAR(50)
  , LASTNAME              VARCHAR(50)
  , FIRSTNAME             VARCHAR(50)
  , PASSWORD              VARCHAR(50)  NOT NULL
  , ROLE_ID               VARCHAR(1)   NOT NULL
  , REGIST_DATE           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
  , REGIST_USER_ID        VARCHAR(10)  NOT NULL
  , UPDATE_DATE           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
  , UPDATE_USER_ID        VARCHAR(10)  NOT NULL
  , VERSION               INTEGER      NOT NULL DEFAULT '0'
  , PRIMARY KEY (USER_ID)
  , UNIQUE (EMAIL)
);
CREATE INDEX ON public.USER (COMPANY_ID);

