CREATE SEQUENCE public.USER_ID_SEQ START 1;
COMMENT ON SEQUENCE public.USER_ID_SEQ IS 'システム内部用のユーザの連番';

CREATE SEQUENCE public.COMPANY_ID_SEQ START 1;
COMMENT ON SEQUENCE public.COMPANY_ID_SEQ IS 'システム内部用の会社の連番';

CREATE TABLE public.ACCOUNT (
    USER_ID               INTEGER NOT NULL DEFAULT nextval('USER_ID_SEQ')
  , EMAIL                 VARCHAR(50)  NOT NULL
  , COMPANY_ID            INTEGER      NOT NULL
  , EMP_CODE              VARCHAR(20)  NOT NULL
  , PASSWORD              VARCHAR(100) NOT NULL
  , LASTNAME              VARCHAR(20)
  , FIRSTNAME             VARCHAR(20)
  , LASTNAME_KANA         VARCHAR(20)
  , FIRSTNAME_KANA        VARCHAR(20)
  , ROLE_ID               VARCHAR(1)   NOT NULL
  , REGIST_DATE           TIMESTAMP    NOT NULL
  , REGIST_USER_ID        INTEGER      NOT NULL
  , UPDATE_DATE           TIMESTAMP    NOT NULL
  , UPDATE_USER_ID        INTEGER      NOT NULL
  , VERSION               INTEGER      NOT NULL
  , PRIMARY KEY (USER_ID)
  , UNIQUE (EMAIL)
  , UNIQUE (COMPANY_ID, EMP_CODE)
);
CREATE INDEX ON public.ACCOUNT (EMAIL);
CREATE INDEX ON public.ACCOUNT (COMPANY_ID);
COMMENT ON TABLE public.ACCOUNT IS 'アカウント';

CREATE TABLE public.COMPANY (
    COMPANY_ID            INTEGER      NOT NULL
  , COMPANY_NAME          VARCHAR(30)  NOT NULL
  , REGIST_DATE           TIMESTAMP    NOT NULL
  , REGIST_USER_ID        INTEGER      NOT NULL
  , UPDATE_DATE           TIMESTAMP    NOT NULL
  , UPDATE_USER_ID        INTEGER      NOT NULL
  , VERSION               INTEGER      NOT NULL
  , PRIMARY KEY (COMPANY_ID)
);
COMMENT ON TABLE public.COMPANY IS '会社';

